version: "1.0"
services:
  mongodb:
    image: mongo:8.0.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  api-server:
    build:
      context: ./api-server
    ports:
      - "4000:4000"
    volumes:
      - ./api-server:/api-server
      - /api-server/node_modules
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
  web-server:
    build:
      context: ./web-server
    ports:
      - "3000:3000"
    volumes:
      - ./web-server:/web-server
      - /web-server/node_modules
    depends_on:
      - api-server

volumes:
  mongo_data:
